kind: "Service"
apiVersion: "v1"
metadata:
  name: "registry"
spec:
  selector:
    app: "registry"
  ports:
    -
      protocol: "TCP"
      port: 5000
      targetPort: 5000
      nodePort: 31500
  type: "NodePort"

