repositories:
  repos:
    - git_url: https://git.openstack.org/openstack/fuel-ccp-cinder
      name: cinder
    - git_url: https://git.openstack.org/openstack/fuel-ccp-debian-base
      name: debian-base
    - git_url: https://git.openstack.org/openstack/fuel-ccp-entrypoint
      name: entrypoint
    - git_url: https://git.openstack.org/openstack/fuel-ccp-etcd
      name: etcd
    - git_url: https://git.openstack.org/openstack/fuel-ccp-glance
      name: glance
    - git_url: https://git.openstack.org/openstack/fuel-ccp-horizon
      name: horizon
    - git_url: https://git.openstack.org/openstack/fuel-ccp-ironic
      name: ironic
    - git_url: https://git.openstack.org/openstack/fuel-ccp-keystone
      name: keystone
    - git_url: https://git.openstack.org/openstack/fuel-ccp-mariadb
      name: mariadb
    - git_url: https://git.openstack.org/openstack/fuel-ccp-memcached
      name: memcached
    - git_url: https://git.openstack.org/openstack/fuel-ccp-murano
      name: murano
    - git_url: https://git.openstack.org/openstack/fuel-ccp-neutron
      name: neutron
    - git_url: https://git.openstack.org/openstack/fuel-ccp-nova
      name: nova
    - git_url: https://git.openstack.org/openstack/fuel-ccp-openstack-base
      name: openstack-base
    - git_url: https://git.openstack.org/openstack/fuel-ccp-rabbitmq
      name: rabbitmq
    - git_url: https://git.openstack.org/openstack/fuel-ccp-sahara
      name: sahara
