apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: NAMESPACE
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  tls:
  - hosts:
    - "*.DOMAIN"
    secretName: nginx-ingress-controller-cert
  rules:
  - host: "*.DOMAIN"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: SERVICE_NAME
          servicePort: SERVICE_PORT
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress-controller
    spec:
      volumes:
      - name: ssl
        secret:
          secretName: nginx-ingress-controller-cert
      - name: nginx-template
        configMap:
          name: nginx-template
          items:
          - key: nginx.tmpl
            path: nginx.tmpl
      terminationGracePeriodSeconds: 60
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.9.0-beta.1
        name: nginx-ingress-controller
        volumeMounts:
          - name: nginx-template
            mountPath: /etc/nginx/template
            readOnly: true
        readinessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: HTTP_PORT
          hostPort: HTTP_PORT
        - containerPort: HTTPS_PORT
          hostPort: HTTPS_PORT
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/nginx-ingress-controller
        - --configmap=$(POD_NAMESPACE)/nginx-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: NAMESPACE
  name: nginx-ingress-controller
spec:
  externalIPs:
    - EXTERNAL_IP
  ports:
    - name: http
      port: HTTP_PORT
    - name: https
      port: HTTPS_PORT
  selector:
    app: nginx-ingress-controller